// possible tests
// test if node installed
// test npm install
// test if jdk is installed
// test if SQLite is installed

// brew services start jenkins
// expose the port & pull from github
// ./ngrok http 8080

pipeline {
  agent any
  stages {
  	stage('Stage 1') {
  		steps {
  			echo 'Hello world 0123456789!'
        echo 'Hello world Test'
        echo 'Hello world Test'
        echo 'Hello world Test'
  		}
  	}
  }
}